version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./chall-1:/app
    environment:
      FLASK_ENV: development

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./chall-1/static:/app/static
    depends_on:
      - app

