version: '3'

services:
  flask1:
    build:
      context: ./chall-1
      dockerfile: Dockerfile-flask1
    ports:
      - "5001:5000"
  
  flask2:
    build:
      context: ./chall-2
      dockerfile: Dockerfile-flask2
    ports:
      - "5002:5000"
  
  node:
    build:
      context: ./chall-3
      dockerfile: Dockerfile-node
    ports:
      - "3000:3000"
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask1
      - flask2
      - node

