version: '3'
services:
  web1:
    image: web1_image
    ports:
      - "8001:80"
  web2:
    image: web2_image
    ports:
      - "8002:80"
  web3:
    image: web3_image
    ports:
      - "8003:80"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
