version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./chall-1:/chall-1
    environment:
      FLASK_ENV: development
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./chall-1/static:/chall-1/static
    depends_on:
      - app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: trevorphilips  
      POSTGRES_PASSWORD: suzy4557
      POSTGRES_DB: flask_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

